### ISSUE TITLE
The app.plugins.plugins['obsidian-echarts'].render(option, this.container) throws an error within the onclick event function.

### ISSUE THREAD

**Issue by CL3709** [cumany/obsidian-echarts#6]
```dataviewjs
// Source data
let tasks = dv.pages('"400_DailyRecords"').file.tasks

const tagsGroups = tasks.map(task => task.tags);
const clientInput = 'Strings';
console.log(clientInput)
// 提取客户和标签计数
const clientTagCounts = {};
tagsGroups.forEach(tagsGroup => {
	const clientTag = tagsGroup.find(tag => tag.startsWith("#客户/"));
	if (clientTag) {
		const client = clientTag.replace("#客户/", "");
		clientTagCounts[client] = clientTagCounts[client] || {};
		tagsGroup.forEach(tag => {
			if (!tag.startsWith("#客户/")) {
				clientTagCounts[client][tag] = (clientTagCounts[client][tag] || 0) + 1;
			}
		});
	}
});
// console.log(clientTagCounts)
// 根据输入的客户名称部分筛选数据
const filteredClientTagCounts = {};
for (const client in clientTagCounts) {
	if (client.includes(clientInput)) {
		filteredClientTagCounts[client] = clientTagCounts[client];
	}
}
// console.log(filteredClientTagCounts)
// 准备数据以绘制柱状图
const xAxisData = Object.keys(filteredClientTagCounts);
console.log(xAxisData)
console.log(filteredClientTagCounts[xAxisData[0]])
const seriesData = [];
for (const tag in filteredClientTagCounts[xAxisData[0]]) {
	const tagData = [];
	for (const client in filteredClientTagCounts) {
		tagData.push(filteredClientTagCounts[client][tag] || 0);
		console.log(tagData)
	}
	seriesData.push({
		name: tag,
		type: 'bar',
		data: tagData
	});
}

// 使用 ECharts 绘制柱状图
const option = {
	tooltip: {
		trigger: 'axis',
		axisPointer: {
			type: 'shadow'
		}
	},
	legend: {
		data: Object.keys(filteredClientTagCounts[xAxisData[0]])
	},
	xAxis: {
		type: 'category',
		data: xAxisData
	},
	yAxis: {
		type: 'value'
	},
	series: seriesData
};

app.plugins.plugins['obsidian-echarts'].render(option, this.container)
```
![image](https://github.com/cumany/obsidian-echarts/assets/140160162/bac4e4a6-0c0b-4754-8b09-52de22c089dc)

这段dataviewjs是正常工作的。/This piece of code is working fine.
但如果我增加一个按钮，将app.plugins.plugins['obsidian-echarts'].render(option, this.container)放在onclick事件函数里，就会报错：/But if I add a button and put app.plugins.plugins['obsidian-echarts'].render(option, this.container) inside the onclick event function, it will throw an error:

```text
plugin:obsidian-echarts:96688 Uncaught TypeError: Cannot read properties of undefined (reading 'createDiv')
    at Renderer.initChart (plugin:obsidian-echarts:96688:35)
    at Renderer.render (plugin:obsidian-echarts:96773:30)
    at EchartsPlugin.render (plugin:obsidian-echarts:96887:18)
    at eleBtn.onclick (eval at <anonymous> (plugin:dataview:1:1), <anonymous>:91:42)
```
![image](https://github.com/cumany/obsidian-echarts/assets/140160162/807a1ca1-2d16-4f2a-b49e-76a7dd311525)

代码是这样的：/The code looks like this:
```dataviewjs


// Tag input
dv.span("  ");
dv.span("Tag: ");
let eleTag = dv.el("input");
eleTag.style.width = "120px";

// Query button
dv.span("  ");
let eleBtn = dv.el("button", "Query");
let MSG = document.getElementById("MSG");

function msg(sMsg) {
  new Notice(sMsg);
  MSG.innerText = sMsg;
}

eleBtn.onclick = function() {
	// Source data
	let tasks = dv.pages('"400_DailyRecords"').file.tasks
	
	const tagsGroups = tasks.map(task => task.tags);
	const clientInput = eleTag.value;
	console.log(clientInput)
	if (!clientInput) {
		return;
	}
	// 提取客户和标签计数
	const clientTagCounts = {};
	tagsGroups.forEach(tagsGroup => {
	    const clientTag = tagsGroup.find(tag => tag.startsWith("#客户/"));
	    if (clientTag) {
	        const client = clientTag.replace("#客户/", "");
	        clientTagCounts[client] = clientTagCounts[client] || {};
	        tagsGroup.forEach(tag => {
	            if (!tag.startsWith("#客户/")) {
	                clientTagCounts[client][tag] = (clientTagCounts[client][tag] || 0) + 1;
	            }
	        });
	    }
	});
	// console.log(clientTagCounts)
	// 根据输入的客户名称部分筛选数据
	const filteredClientTagCounts = {};
	for (const client in clientTagCounts) {
	    if (client.includes(clientInput)) {
	        filteredClientTagCounts[client] = clientTagCounts[client];
	    }
	}
	// console.log(filteredClientTagCounts)
	// 准备数据以绘制柱状图
	const xAxisData = Object.keys(filteredClientTagCounts);
	console.log(xAxisData)
	console.log(filteredClientTagCounts[xAxisData[0]])
	const seriesData = [];
	for (const tag in filteredClientTagCounts[xAxisData[0]]) {
	    const tagData = [];
	    for (const client in filteredClientTagCounts) {
	        tagData.push(filteredClientTagCounts[client][tag] || 0);
	        console.log(tagData)
	    }
	    seriesData.push({
	        name: tag,
	        type: 'bar',
	        data: tagData
	    });
	}

	// 使用 ECharts 绘制柱状图
	const option = {
	    tooltip: {
	        trigger: 'axis',
	        axisPointer: {
	            type: 'shadow'
	        }
	    },
	    legend: {
	        data: Object.keys(filteredClientTagCounts[xAxisData[0]])
	    },
	    xAxis: {
	        type: 'category',
	        data: xAxisData
	    },
	    yAxis: {
	        type: 'value'
	    },
	    series: seriesData
	};
	
	app.plugins.plugins['obsidian-echarts'].render(option, this.container)
}

```

**Comment by CL3709** [comment]
this.container参数需要传进函数里
var containerVarNeeded = this.container
function() {
    app.plugins.plugins['obsidian-echarts'].render(option, containerVarNeeded)
}

**Comment by Lilin-space** [comment]
Hello, can you share the final code? I also have this confusion, but I don't understand this solution

**Comment by CL3709** [comment]
I'm not entirely sure either, but it seems that the layout container obtained through this.container is different in the editing area and within the function. In fact, in the editing area, you can directly pass this.container, save it in a variable, and then pass that variable into the function. From the results, this approach seems to work.


These are the final complete codes.


// Tag input
dv.span("&nbsp; ");
dv.span("Tag: ");
let eleTag = dv.el("input");
eleTag.style.width = "120px";


// Query button
dv.span("&nbsp; ");
let eleBtn = dv.el("button", "Query");
let MSG = document.getElementById("MSG");


function msg(sMsg) {
&nbsp; new Notice(sMsg);
&nbsp; MSG.innerText = sMsg;
}


// get this.container in the editing area
var containerEditingArea = this.container


eleBtn.onclick = function() {
	// Source data
	let tasks = dv.pages('"400_DailyRecords"').file.tasks
	
	const tagsGroups = tasks.map(task =&gt; task.tags);
	const clientInput = eleTag.value;
	console.log(clientInput)
	if (!clientInput) {
		return;
	}
	// 提取客户和标签计数
	const clientTagCounts = {};
	tagsGroups.forEach(tagsGroup =&gt; {
	&nbsp; &nbsp; const clientTag = tagsGroup.find(tag =&gt; tag.startsWith("#客户/"));
	&nbsp; &nbsp; if (clientTag) {
	&nbsp; &nbsp; &nbsp; &nbsp; const client = clientTag.replace("#客户/", "");
	&nbsp; &nbsp; &nbsp; &nbsp; clientTagCounts[client] = clientTagCounts[client] || {};
	&nbsp; &nbsp; &nbsp; &nbsp; tagsGroup.forEach(tag =&gt; {
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (!tag.startsWith("#客户/")) {
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; clientTagCounts[client][tag] = (clientTagCounts[client][tag] || 0) + 1;
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
	&nbsp; &nbsp; &nbsp; &nbsp; });
	&nbsp; &nbsp; }
	});
	// console.log(clientTagCounts)
	// 根据输入的客户名称部分筛选数据
	const filteredClientTagCounts = {};
	for (const client in clientTagCounts) {
	&nbsp; &nbsp; if (client.includes(clientInput)) {
	&nbsp; &nbsp; &nbsp; &nbsp; filteredClientTagCounts[client] = clientTagCounts[client];
	&nbsp; &nbsp; }
	}
	// console.log(filteredClientTagCounts)
	// 准备数据以绘制柱状图
	const xAxisData = Object.keys(filteredClientTagCounts);
	console.log(xAxisData)
	console.log(filteredClientTagCounts[xAxisData[0]])
	const seriesData = [];
	for (const tag in filteredClientTagCounts[xAxisData[0]]) {
	&nbsp; &nbsp; const tagData = [];
	&nbsp; &nbsp; for (const client in filteredClientTagCounts) {
	&nbsp; &nbsp; &nbsp; &nbsp; tagData.push(filteredClientTagCounts[client][tag] || 0);
	&nbsp; &nbsp; &nbsp; &nbsp; console.log(tagData)
	&nbsp; &nbsp; }
	&nbsp; &nbsp; seriesData.push({
	&nbsp; &nbsp; &nbsp; &nbsp; name: tag,
	&nbsp; &nbsp; &nbsp; &nbsp; type: 'bar',
	&nbsp; &nbsp; &nbsp; &nbsp; data: tagData
	&nbsp; &nbsp; });
	}


	// 使用 ECharts 绘制柱状图
	const option = {
	&nbsp; &nbsp; tooltip: {
	&nbsp; &nbsp; &nbsp; &nbsp; trigger: 'axis',
	&nbsp; &nbsp; &nbsp; &nbsp; axisPointer: {
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; type: 'shadow'
	&nbsp; &nbsp; &nbsp; &nbsp; }
	&nbsp; &nbsp; },
	&nbsp; &nbsp; legend: {
	&nbsp; &nbsp; &nbsp; &nbsp; data: Object.keys(filteredClientTagCounts[xAxisData[0]])
	&nbsp; &nbsp; },
	&nbsp; &nbsp; xAxis: {
	&nbsp; &nbsp; &nbsp; &nbsp; type: 'category',
	&nbsp; &nbsp; &nbsp; &nbsp; data: xAxisData
	&nbsp; &nbsp; },
	&nbsp; &nbsp; yAxis: {
	&nbsp; &nbsp; &nbsp; &nbsp; type: 'value'
	&nbsp; &nbsp; },
	&nbsp; &nbsp; series: seriesData
	};
	
	// app.plugins.plugins['obsidian-echarts'].render(option, this.container)
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;app.plugins.plugins['obsidian-echarts'].render(option, containerEditingArea)
}







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cumany/obsidian-echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月19日(星期天) 上午10:10
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [cumany/obsidian-echarts] The app.plugins.plugins['obsidian-echarts'].render(option, this.container) throws an error within the onclick event function. (Issue #6)





 
Hello, can you share the final code? I also have this confusion, but I don't understand this solution

**Comment by CL3709** [comment]
I'm not entirely sure either, but it seems that the layout container obtained through this.container is different in the editing area and within the function. In fact, in the editing area, you can directly pass this.container. So, I'm considering saving it in a variable and then passing that variable into the function. From the results, this approach seems to work.


These are the final complete codes.


// Tag input
dv.span("&nbsp; ");
dv.span("Tag: ");
let eleTag = dv.el("input");
eleTag.style.width = "120px";


// Query button
dv.span("&nbsp; ");
let eleBtn = dv.el("button", "Query");
let MSG = document.getElementById("MSG");


function msg(sMsg) {
&nbsp; new Notice(sMsg);
&nbsp; MSG.innerText = sMsg;
}


// get this.container in the editing area
var containerEditingArea = this.container


eleBtn.onclick = function() {
	// Source data
	let tasks = dv.pages('"400_DailyRecords"').file.tasks
	
	const tagsGroups = tasks.map(task =&gt; task.tags);
	const clientInput = eleTag.value;
	console.log(clientInput)
	if (!clientInput) {
		return;
	}
	// 提取客户和标签计数
	const clientTagCounts = {};
	tagsGroups.forEach(tagsGroup =&gt; {
	&nbsp; &nbsp; const clientTag = tagsGroup.find(tag =&gt; tag.startsWith("#客户/"));
	&nbsp; &nbsp; if (clientTag) {
	&nbsp; &nbsp; &nbsp; &nbsp; const client = clientTag.replace("#客户/", "");
	&nbsp; &nbsp; &nbsp; &nbsp; clientTagCounts[client] = clientTagCounts[client] || {};
	&nbsp; &nbsp; &nbsp; &nbsp; tagsGroup.forEach(tag =&gt; {
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (!tag.startsWith("#客户/")) {
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; clientTagCounts[client][tag] = (clientTagCounts[client][tag] || 0) + 1;
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
	&nbsp; &nbsp; &nbsp; &nbsp; });
	&nbsp; &nbsp; }
	});
	// console.log(clientTagCounts)
	// 根据输入的客户名称部分筛选数据
	const filteredClientTagCounts = {};
	for (const client in clientTagCounts) {
	&nbsp; &nbsp; if (client.includes(clientInput)) {
	&nbsp; &nbsp; &nbsp; &nbsp; filteredClientTagCounts[client] = clientTagCounts[client];
	&nbsp; &nbsp; }
	}
	// console.log(filteredClientTagCounts)
	// 准备数据以绘制柱状图
	const xAxisData = Object.keys(filteredClientTagCounts);
	console.log(xAxisData)
	console.log(filteredClientTagCounts[xAxisData[0]])
	const seriesData = [];
	for (const tag in filteredClientTagCounts[xAxisData[0]]) {
	&nbsp; &nbsp; const tagData = [];
	&nbsp; &nbsp; for (const client in filteredClientTagCounts) {
	&nbsp; &nbsp; &nbsp; &nbsp; tagData.push(filteredClientTagCounts[client][tag] || 0);
	&nbsp; &nbsp; &nbsp; &nbsp; console.log(tagData)
	&nbsp; &nbsp; }
	&nbsp; &nbsp; seriesData.push({
	&nbsp; &nbsp; &nbsp; &nbsp; name: tag,
	&nbsp; &nbsp; &nbsp; &nbsp; type: 'bar',
	&nbsp; &nbsp; &nbsp; &nbsp; data: tagData
	&nbsp; &nbsp; });
	}


	// 使用 ECharts 绘制柱状图
	const option = {
	&nbsp; &nbsp; tooltip: {
	&nbsp; &nbsp; &nbsp; &nbsp; trigger: 'axis',
	&nbsp; &nbsp; &nbsp; &nbsp; axisPointer: {
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; type: 'shadow'
	&nbsp; &nbsp; &nbsp; &nbsp; }
	&nbsp; &nbsp; },
	&nbsp; &nbsp; legend: {
	&nbsp; &nbsp; &nbsp; &nbsp; data: Object.keys(filteredClientTagCounts[xAxisData[0]])
	&nbsp; &nbsp; },
	&nbsp; &nbsp; xAxis: {
	&nbsp; &nbsp; &nbsp; &nbsp; type: 'category',
	&nbsp; &nbsp; &nbsp; &nbsp; data: xAxisData
	&nbsp; &nbsp; },
	&nbsp; &nbsp; yAxis: {
	&nbsp; &nbsp; &nbsp; &nbsp; type: 'value'
	&nbsp; &nbsp; },
	&nbsp; &nbsp; series: seriesData
	};
	
	// app.plugins.plugins['obsidian-echarts'].render(option, this.container)
&nbsp; &nbsp; &nbsp; &nbsp; app.plugins.plugins['obsidian-echarts'].render(option, containerEditingArea)
}







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "cumany/obsidian-echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月19日(星期天) 上午10:10
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [cumany/obsidian-echarts] The app.plugins.plugins['obsidian-echarts'].render(option, this.container) throws an error within the onclick event function. (Issue #6)





 
Hello, can you share the final code? I also have this confusion, but I don't understand this solution
